### ISSUE TITLE
Please include a typings file for TypeScript projects

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#73]
thank you!

**Comment by swese44** [comment]
here's the placeholder we're using, which is compatible with the latest release. this is definitely not perfect but it works for now

```
declare module 'screener-storybook/src/screener' {
  export type Key =
    | 'alt'
    | 'control'
    | 'enter'
    | 'escape'
    | 'return'
    | 'shift'
    | 'tab'
    | 'leftArrow'
    | 'upArrow'
    | 'rightArrow'
    | 'downArrow';

  export const Keys: Record<Key, string>;

  export interface Steps {
    click(selector: string): Steps;
    cssAnimations(enabled: boolean): Steps;
    snapshot(name: string, options?: any[]): Steps;
    focus(selector: string): Steps;
    hover(selector: string): Steps;
    mouseDown(selector: string): Steps;
    mouseUp(selector: string): Steps;
    keys(selector: string, key: string): Steps;
    setValue(selector: string, value: string): Steps;
    executeScript(code: string): Steps;
    ignore(selector: string): Steps;
    wait(val: number | string): Steps;
    rtl(): Steps;
    ltr(): Steps;
    end(): Steps;
  }

  // tslint:disable-next-line
  export class Steps implements Steps {}

  export interface ScreenerProps {
    steps?: Steps;
    isScreenerComponent?: boolean;
  }

  export default class Screener extends React.Component<ScreenerProps> {}
}
```

**Comment by loyalchow** [comment]
Thanks @swese44!

**Comment by loyalchow** [comment]
@swese44 Added typings file in release v0.15.1

**Comment by swese44** [comment]
your team is awesome, thanks again!

**Comment by ecraig12345** [comment]
At least in my project, the new typings file isn't being detected. Wondering if that has to do with either the way the module is declared, or the fact that it's using `React` without declaring a dependency on `@types/react`? (Happy to open a new issue if you prefer.)

**Comment by loyalchow** [comment]
Hi @ecraig12345, can you reference it?

```
/// <reference types="screener-storybook" />
```

**Comment by ecraig12345** [comment]
With the explicit reference added I do get intellisense, but it's broken because of the missing reference to the React types in the typings file. (Screenshot is from [this file](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/vr-tests/src/stories/ContextualMenu.stories.tsx) opened in VS Code, but I could try to get a simpler repro if you want.) I'm also surprised the explicit reference is needed since types are usually picked up automatically.

![image](https://user-images.githubusercontent.com/5864305/51002138-37f03200-14e7-11e9-85ae-6674fb77d281.png)

**Comment by ecraig12345** [comment]
Actually thinking about it more this may mostly be user error, sorry... My project's tsconfig.json has the `types` setting defined (which IIRC prevents types from automatically being picked up from npm packages), so `screener-storybook` needs to be added to that list.

The error in the latest screenshot in my previous comment is because `isScreenerComponent` is marked as required in the type definitions but absent in our code and in the [examples](https://screener.io/v2/docs/test-interactions). So guessing the type definitions should be updated to make that property optional?

**Comment by loyalchow** [comment]
@ecraig12345 sounds good, just updated in https://github.com/screener-io/screener-storybook/pull/85

`screener-storybook` version updated to v0.16.7

**Comment by ecraig12345** [comment]
Thanks very much!

**Comment by swese44** [comment]
or more granular *.d.ts files can live next to each .js file to define their exported modules

**Comment by swese44** [comment]
it also looks like there are a few issues with the latest version of the typings file, which i've copied into our local file at `./typings/screener-storybook.d.ts`:

- `Steps.end()` returns an arbitrary array instead of `Steps` which fails the compiler, not sure why that was changed. I've reverted this change in our local override to allow the app to compile.
- `ScreenerProps.isScreenerComponent` was changed from optional to required, which doesn't make sense because digging into the implementation it's setting a default value to `true` via `defaultProps`. I've reverted this change locally, otherwise it would require us to pass `isScreenerComponent={true}` every time we use the `<Screener>` component

**Comment by ecraig12345** [comment]
Based on [the `Steps` code](https://github.com/screener-io/screener-runner/blob/master/src/steps.js), an array of step objects is the correct return type. Maybe whichever code is consuming what's returned from `Steps.end()` needs to be updated?

**Comment by ecraig12345** [comment]
Also not sure what you mean about `isScreenerComponent` being required. In the very latest version, it's optional. 
https://github.com/screener-io/screener-storybook/blob/cb63707a0366cb30eae8520a2f428c14dec31997/index.d.ts#L83-L90

**Comment by swese44** [comment]
ah thanks @ecraig12345, i didn't have the latest version. you're right, ignore everything i said about the typings file! 😳

**Comment by swese44** [comment]
i tried to update our project to add "screener-storybook" to "types" or "typeRoots" in tsconfig.json like Fabric's `vr-tests` app is doing, but this excludes other type packages we rely on. for now we'll have to live with a copy of `index.d.ts` in our `./typings/` folder and update it whenever we version-bump `screener-storybook`. no rush here, but it would be nice if `screener-storybook` could eventually have `*.d.ts` files live in the same level as their exports
