### ISSUE TITLE
Enter key doesn't seem to work for IE11

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#77]
This works in Chrome, but the dropdown does not get its new item selected on `enter` for IE11. I had added the `wait()` calls to see if it was a timing issue with the screenshots, but it didn't change the outcome. I've manually tested in IE11 and the real interaction works as expected (hover text field, click text field to open dropdown menu, arrow down while input has focus to select the next item, "enter" to select that next item).

```javascript
<Screener
  steps={new Steps()
    .hover('.y-dropdown .ms-Dropdown')
    .snapshot('hover')
    .click('.y-dropdown .ms-Dropdown')
    .snapshot('click open')
    .wait(50)
    .keys('.y-dropdown .ms-Dropdown', Keys.downArrow)
    .wait(50)
    .keys('.y-dropdown .ms-Dropdown', Keys.enter)
    .wait(50)
    .snapshot('enter select item')
    .end()}
>
  <ControlledDropdown />
</Screener>
```

Can you verify in your own test harness whether the "enter" event is working in IE11? thanks

**Comment by loyalchow** [comment]
@swese44 Yes, we've verified that the `enter` key event is triggered on IE11.

_However_ - we have set IE11 to use non-native events by default. So I think your app requires native events to work, not simulated events, which may be causing your issue.

To enable native events on IE11, add the following option to your screener.config.js file:

```
  ieNativeEvents: true
```

FYI: the reason we've disabled native events by default, is because IE11 is known to be inconsistent with native events, which causes React to potentially "lose"  user input when it is re-rendering.

Here are additional links found on this issue:
https://github.com/facebook/react/issues/7027
https://github.com/reagent-project/reagent/issues/253
https://github.com/omcljs/om/issues/704

**Comment by swese44** [comment]
i'll test this, thank you

**Comment by swese44** [comment]
this was the solution, thanks again!

**Comment by loyalchow** [comment]
Great! 👍
